@extends('backend.layouts.master')

@section('admin-content')
<style>
    .ri-page{background:#f3f6fb;padding:4px;border-radius:22px}.ri-hero,.ri-card{background:#fff;border:1px solid #dbe5f1;border-radius:22px;padding:22px;margin-bottom:16px;box-shadow:0 12px 35px rgba(15,23,42,.05)}.ri-top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap}.ri-kicker{color:#2563eb;font-size:13px;font-weight:900;margin-bottom:6px}.ri-title{margin:0;font-size:30px;font-weight:950;color:#020617}.ri-sub{margin:8px 0 0;color:#526783}.ri-back,.ri-btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:10px 18px;border-radius:12px;border:1px solid #cbd5e1;background:#f8fafc;color:#020617;font-weight:900;text-decoration:none}.ri-btn{border:0;background:#2563eb;color:#fff}.ri-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-top:22px}.ri-stat{background:linear-gradient(180deg,#fff,#f8fbff);border:1px solid #dbe5f1;border-radius:16px;padding:17px 15px}.ri-stat span{display:block;font-size:12px;color:#526783;font-weight:900;text-transform:uppercase;margin-bottom:12px}.ri-stat strong{display:block;font-size:23px;color:#020617;font-weight:950}.ri-filter{display:flex;align-items:end;gap:10px;flex-wrap:wrap}.ri-field label{display:block;font-size:12px;color:#0f172a;font-weight:900;margin-bottom:8px}.ri-select{height:43px;border:1px solid #cbd5e1;border-radius:11px;padding:8px 12px;background:#fff}.ri-table-wrap{overflow-x:auto}.ri-table{width:100%;border-collapse:separate;border-spacing:0 10px;min-width:1050px}.ri-table th{text-align:left;color:#526783;font-size:12px;font-weight:900;text-transform:uppercase;padding:0 12px 11px;border-bottom:1px solid #e5e7eb}.ri-table td{background:#f8fbff;border-top:1px solid #dbe5f1;border-bottom:1px solid #dbe5f1;padding:14px 12px;vertical-align:middle}.ri-table td:first-child{border-left:1px solid #dbe5f1;border-radius:14px 0 0 14px}.ri-table td:last-child{border-right:1px solid #dbe5f1;border-radius:0 14px 14px 0}.ri-main{font-size:15px;color:#020617;font-weight:900;margin-bottom:5px}.ri-small{font-size:12px;color:#526783}.ri-pill{display:inline-flex;padding:8px 12px;border-radius:999px;font-size:12px;font-weight:900;background:#e0f2fe;color:#0369a1}.ri-status.paid{background:#dcfce7;color:#166534}.ri-status.open{background:#fef3c7;color:#92400e}.ri-status.unpaid,.ri-status.void{background:#fee2e2;color:#991b1b}.ri-actions{display:flex;gap:8px;flex-wrap:wrap}.ri-view{background:#f8fafc;color:#020617;border:1px solid #cbd5e1;border-radius:11px;padding:10px 17px;text-decoration:none;font-weight:950}.ri-stripe{background:#16a34a;color:#fff;border-radius:11px;padding:11px 18px;text-decoration:none;font-weight:950}@media(max-width:1200px){.ri-stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:768px){.ri-stats{grid-template-columns:1fr}.ri-title{font-size:24px}.ri-back,.ri-btn,.ri-field{width:100%}}
</style>
<div class="ri-page">
    <div class="ri-hero">
        <div class="ri-top">
            <div><div class="ri-kicker">Sponsored Route Slots</div><h1 class="ri-title">Route Featured Invoices</h1><p class="ri-sub">Manage all route featured ads invoice revenue.</p></div>
            
        </div>
        <div class="ri-stats">
            <div class="ri-stat"><span>Total Revenue</span><strong>${{ number_format(($totalRevenueCents ?? 0) / 100, 2) }}</strong></div>
            <div class="ri-stat"><span>This Month</span><strong>${{ number_format(($thisMonthRevenueCents ?? 0) / 100, 2) }}</strong></div>
            <div class="ri-stat"><span>Filtered Revenue</span><strong>${{ number_format(($filteredRevenueCents ?? 0) / 100, 2) }}</strong></div>
            
            <div class="ri-stat"><span>Paid Invoices</span><strong>{{ $paidInvoicesCount ?? 0 }}</strong></div>
        </div>
    </div>
    <div class="ri-card"><form method="GET" class="ri-filter"><div class="ri-field"><label>Status</label><select name="status" class="ri-select"><option value="">All</option><option value="paid" @selected(($selectedStatus ?? '') === 'paid')>Paid</option><option value="open" @selected(($selectedStatus ?? '') === 'open')>Open</option><option value="unpaid" @selected(($selectedStatus ?? '') === 'unpaid')>Unpaid</option><option value="void" @selected(($selectedStatus ?? '') === 'void')>Void</option></select></div><div class="ri-field"><label>Billing</label><select name="billing" class="ri-select"><option value="">All</option><option value="monthly" @selected(($selectedBilling ?? '') === 'monthly')>Monthly</option><option value="yearly" @selected(($selectedBilling ?? '') === 'yearly')>Yearly</option></select></div><button class="ri-btn" type="submit">Apply Filter</button>@if(!empty($selectedStatus) || !empty($selectedBilling))<a href="{{ url()->current() }}" class="ri-back">Clear</a>@endif</form></div>
    <div class="ri-card"><div class="ri-table-wrap"><table class="ri-table"><thead><tr><th>Invoice</th><th>Route / Slot</th><th>Billing</th><th>Period</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($invoices as $invoice)@php $subscription=$invoice->subscription; $invoiceNo='INV-'.str_pad($invoice->id,5,'0',STR_PAD_LEFT); $status=strtolower($invoice->status ?? '-'); @endphp<tr><td><div class="ri-main">{{ $invoiceNo }}</div><div class="ri-small">{{ optional($invoice->paid_at)->format('M d, Y h:i A') ?? optional($invoice->created_at)->format('M d, Y h:i A') }}</div></td><td><div class="ri-main">{{ optional($subscription)->routeName() ?? '-' }}</div><div class="ri-small">Slot {{ optional(optional($subscription)->slot)->slot_number ?? '-' }}</div></td><td><span class="ri-pill">{{ ucfirst(optional($subscription)->billing_cycle ?? '-') }}</span></td><td><div class="ri-main">{{ optional($invoice->period_start)->format('M d, Y') ?? '-' }}</div><div class="ri-small">to {{ optional($invoice->period_end)->format('M d, Y') ?? '-' }}</div></td><td><div class="ri-main">{{ strtoupper($invoice->currency ?? 'USD') }} {{ number_format(($invoice->amount_paid_cents ?? 0) / 100, 2) }}</div></td><td><span class="ri-pill ri-status {{ $status }}">{{ ucfirst($status) }}</span></td><td><div class="ri-actions"><a class="ri-view" href="{{ route('admin.route-featured-invoices.show', $invoice->id) }}">View</a>@if(!empty($invoice->hosted_invoice_url))<a class="ri-stripe" href="{{ $invoice->hosted_invoice_url }}" target="_blank">Stripe</a>@endif</div></td></tr>@empty<tr><td colspan="7"><div style="text-align:center;padding:30px;color:#64748b;font-weight:800">No invoices found.</div></td></tr>@endforelse</tbody></table></div>{{ $invoices->links() }}</div>
</div>
@endsection
