<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Moving Leads Report</title>

    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #2c3e50;
            margin: 25px;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #2c3e50;
            padding-bottom: 12px;
            margin-bottom: 20px;
        }

        .company-name {
            font-size: 22px;
            font-weight: bold;
        }

        .report-title {
            font-size: 16px;
            margin-top: 4px;
            color: #555;
        }

        .date-range {
            font-size: 11px;
            color: #777;
        }

        .summary {
            background: #f4f6f8;
            padding: 10px 14px;
            border-left: 4px solid #2c3e50;
            margin-bottom: 18px;
            font-weight: bold;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        thead {
            background: #2c3e50;
            color: #ffffff;
        }

        th {
            padding: 10px;
            font-size: 12px;
            text-align: left;
        }

        td {
            padding: 9px;
            font-size: 12px;
            vertical-align: top;
            word-break: break-word;
            white-space: normal;
            border-bottom: 1px solid #e5e5e5;
        }

        tbody tr:nth-child(even) {
            background: #fafafa;
        }

        .badge {
            padding: 3px 7px;
            border-radius: 4px;
            font-size: 10px;
            background: #ecf0f1;
        }

        .footer {
            position: fixed;
            bottom: 10px;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 10px;
            color: #888;
        }

        .page-number:after {
            content: counter(page);
        }
    </style>
</head>

<body>
    <div class="header">
        <table width="100%" cellspacing="0" cellpadding="0" style="border-bottom:2px solid #2c3e50; margin-bottom:15px;">
            <tr>
                <td width="20%" style="text-align:left;">
                    <img src="{{ public_path('assets/image/logo/logo.png') }}" style="height:60px;">
                </td>
                <td width="60%" style="text-align:center;">
                    <div style="font-size:22px;font-weight:bold;">
                        {{ auth('company')->user()->company_name ?? 'Company Name' }}
                    </div>
                    <div style="font-size:16px;color:#555;margin-top:4px;">Moving Leads Report</div>
                    <div style="font-size:12px;color:#888;margin-top:3px;"> Generated:
                        {{ now()->format('d M Y h:i A') }}</div>
                </td>
                <td width="20%"></td>
            </tr>
        </table>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Customer Name</th>
                    <th>Email</th>
                    <th>Move Details</th>
                    <th>Move From</th>
                    <th>Move To </th>
                    <th>Status</th>
                    <th>Date</th>
                </tr>
            </thead>

            <tbody>
                @forelse($quotes as $quote)
                    <tr>
                        <td>#{{ 20000 + $loop->iteration }}</td>
                        <td>{{ $quote->name ?? '-' }}</td>
                        <td>{{ $quote->email ?? '-' }}</td>
                        <td>{{ $quote->move_size ?? '-' }}<br> {{ $quote->date ?? '-' }}</td>
                        <td>{{ $quote->zip_from ?? '-' }}</td>
                        <td>{{ $quote->zip_to ?? '-' }}</td>
                        <td>
                            @php $stage = $quote->currentStage(); @endphp
                            <span class="badge">{{ ucfirst(str_replace('_', ' ', $stage)) }}</span>
                        </td>
                        <td> {{ optional($quote->created_at)->format('d-m-Y') }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="8" style="text-align:center;padding:20px;">
                            No Records Found
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
        <div class="footer">
            © {{ date('Y') }} {{ auth('company')->user()->company_name ?? 'Company' }}
            — Generated by System | Page <span class="page-number"></span>
        </div>

</body>

</html>
