@extends('layouts.app')

@section('title')
    Terms of Service - My Moving Journey
@endsection

@section('meta_description')
    Review the Terms of Service for My Moving Journey to understand the rules and guidelines for using our website and

    services..
@endsection
@section('meta_keywords', 'Terms of Service')

<style>
    h1 {
        font-size: 38px;
        line-height: 40px;
    }

    h2 {
        font-size: 30px !important;
        line-height: 40px;
    }

    .Site_link {
        text-decoration: underline;
        color: var(--bg) !important;
    }

    .about-section p {
        font-size: 17px;
        line-height: 30px
    }

    .about-section ul li {
        font-size: 17px;
        font-family: var(--para-family), sans-serif;
        line-height: 30px
    }

    @media (min-width: 320px) and (max-width: 576px) {
        h1 {
            font-size: 32px !important;
            line-height: 40px;
        }

        main.pb-0 {
            margin-top: 120px !important;
        }

        h2 {
            font-size: 28px !important;
            line-height: 40px;
        }
    }
</style>

@section('content')
    <div class="mask d-flex align-items-center gradient-custom-3 w-100">

        <div class="container">

            <div class="row d-flex justify-content-center align-items-center">

                <div id="company-dashboard-main" class="card row py-0 px-0">

                    <div class="row p-0 m-auto bg-of-aqua-shade">

                        <div class="col-md-9 col-12 m-auto py-3 dash-col2  bg-of-aqua-shade border-0">
                            <nav style="--bs-breadcrumb-divider: '➜';" aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Terms of Service</li>
                                </ol>
                            </nav>
                            <section class="section about-section gray-bg" id="about-dash">

                                <div class="container p-0">

                                    <div class="row">

                                        <h1 class="my-2 fw-bold">Terms of Service</h1>

                                        <p>Welcome to <strong><a class="Site_link" target="blank" href="/">My Moving
                                                    Journey</a></strong> ("Our Website"),
                                            operated by Repo Studio Limited and its subsidiaries and affiliates
                                            (collectively referred to as "we," "us," or "our"). These Terms of Service
                                            ("Terms") govern your use of our website and its services. </p>

                                        <p>By accessing or using the Website, you agree to be bound by
                                            these Terms. If you do not agree with these Terms, you should discontinue
                                            use of our Website immediately.</p>

                                        <p>We reserve the right to revise, modify, or update these Terms
                                            of Service at any time. Changes will be posted on this page, and it is your
                                            responsibility to review these Terms regularly. Continued use of our Website
                                            after such changes signifies your acceptance of the updated Terms.</p>

                                        <h2 class="mt-4">1. General Overview of Our Website</h2>

                                        <p>The <strong> <a class="Site_link" target="blank"
                                                    href="https://mymovingjourney.com/">www.mymovingjourney.com</a></strong>
                                            platform
                                            hosts a wide variety of content, including text, images, videos, logos,
                                            trademarks, service marks, and other materials (collectively referred to as
                                            "Content"). This Content is made available to website users and includes
                                            materials generated by both us and third parties. Our website serves as a
                                            conduit for third-party Content, and while we facilitate access to this
                                            information, we do not guarantee its accuracy or integrity.</p>

                                        <p>The Content displayed on the Website is for informational
                                            purposes and is not intended to replace professional advice. The website is
                                            not responsible for any Content posted by users or third parties. Please be
                                            cautious when using the Website and remember to verify the information you
                                            encounter.</p>



                                        <h2 class="mt-4">2. Submitting a Quote Request</h2>

                                        <p>By submitting a quote request via our Website, you certify
                                            that you are at least 18 years old and agree to receive phone and email
                                            communications from <strong><a class=" Site_link" target="blank"
                                                    href="https://mymovingjourney.com/">www.mymovingjourney.com</a></strong>
                                            and its partners regarding your
                                            request for a moving estimate. </p>

                                        <p>This may include automated calls or messages, including your
                                            cellular number. Your consent to receive such communications is voluntary
                                            and does not impact your ability to make a purchase from us. </p>



                                        <h2 class="mt-4">3. Account Security</h2>

                                        <p>Upon becoming a member of our website and creating an account,
                                            you will receive a password and a unique account identifier. You are
                                            responsible for maintaining the confidentiality of your account details and
                                            password. You agree to notify us promptly if you suspect any unauthorized
                                            access to your account.</p>

                                        <p>You must log out after using your account to protect your
                                            privacy and ensure that no unauthorized individuals can access your
                                            information. We are not responsible for any losses or damages caused by your
                                            failure to safeguard your account information.</p>

                                        <h2 class="mt-4">4. Review Submission Guidelines</h2>

                                        <p>Before posting a review, please ensure that your submission
                                            follows these guidelines:</p>

                                        <ul class="mx-4" style="font-size: 1.25rem; line-height: 32px;">

                                            <li>

                                                <strong>Relevance:</strong> Focus on the service or product and avoid
                                                unrelated issues like employment practices or political views.

                                            </li>

                                            <li>

                                                <strong>Respect:</strong> Offensive language, hate speech, harassment,
                                                and threats will not be tolerated.

                                            </li>

                                            <li>

                                                <strong>Honesty:</strong> Reviews should be based on your personal
                                                experiences with the service or product. Do not post fabricated
                                                information.

                                            </li>

                                            <li>

                                                <strong>Privacy:</strong> Do not share private details about other
                                                individuals; only post photos you have the right to share.

                                            </li>

                                            <li>

                                                <strong>Originality:</strong> Only post original content. Do not copy
                                                reviews from other sources.

                                            </li>

                                        </ul>

                                        <p>You are responsible for the content of your reviews. Any
                                            reviews found to be misleading or in violation of these guidelines may be
                                            removed or modified.</p>

                                        <h2 class="mt-4">5. Guidelines for Business Profiles</h2>

                                        <p>When editing or managing your business profile on our Website,
                                            please adhere to the following rules:</p>

                                        <ul class="mx-4" style="font-size: 1.25rem; line-height: 32px;">

                                            <li>

                                                <strong>Content: </strong>Keep your business information relevant and
                                                free from attacks on competitors or reviewers. Avoid promoting
                                                irrelevant offers or unrelated promotions.

                                            </li>

                                            <li>

                                                <strong>Public Responses: </strong>Business owners are welcome to
                                                respond to customer reviews but must refrain from using this feature to
                                                engage in personal attacks or attempt to influence reviewers through
                                                incentives.

                                            </li>



                                        </ul>

                                        <h2 class="mt-4">6. Your Rights to Content</h2>

                                        <p>The Content you post on our Website remains your property, and
                                            you can request removal of your Content at any time by contacting us at
                                            contact@mymovingjourney.com. However, by posting Content on our site, you
                                            grant us a non-exclusive, royalty-free, worldwide license to use, modify,
                                            and display your Content.</p>

                                        <p>You may not use, distribute, or alter any Content found on the
                                            Website for commercial purposes without our prior consent unless you are the
                                            original creator of the material.</p>

                                        <h2 class="mt-4">7. License Granted to Us for Your Content</h2>

                                        <p>By uploading or submitting Content to our Website, you provide
                                            us with a non-exclusive, worldwide license to use, display, and modify your
                                            Content for purposes related to the operation and promotion of the Website.
                                            This license remains active as long as your Content is on our Website and
                                            terminates when you remove your Content from the site.</p>

                                        <h2 class="mt-4">8. Acceptable Use of Our Website</h2>

                                        <p>You are responsible for the Content you post or share on our
                                            Website. By using our services, you agree not to:</p>

                                        <ul class="mx-4" style="font-size: 1.25rem; line-height: 32px;">

                                            <li>

                                                Post harmful, defamatory, illegal, or offensive material.

                                            </li>

                                            <li>

                                                Share private information about others without their consent. </li>

                                            <li>

                                                Violate the intellectual property rights of others. </li>

                                            <li>

                                                Use the Website for spam or unauthorized advertising purposes.

                                            </li>

                                            <li>

                                                Interfere with or disrupt the Website's functionality.

                                            </li>

                                        </ul>

                                        <h2 class="mt-4">9. Authority to Remove Content or Block Access

                                        </h2>

                                        <p>While we do not actively monitor all user-generated content,
                                            we reserve the right to remove or block access to any material we deem to be
                                            in violation of these Terms of Service. If we take such action, it will be
                                            at our sole discretion and without prior notice. We are not responsible for
                                            any consequences resulting from our removal of your Content or suspension of
                                            your account.</p>

                                        <h2 class="mt-4">10. Advertising and Promotions</h2>

                                        <p>We may display advertisements or third-party content alongside
                                            your posts. By using the Website, you acknowledge and agree that we may
                                            display these ads without compensating you or obtaining further consent. You
                                            agree not to obstruct or interfere with these advertisements in any way.</p>

                                        <h2 class="mt-4">11. Limitation of Liability</h2>

                                        <p>We provide the Website and its Content "as is" without any
                                            warranties of any kind, either express or implied. We do not guarantee that
                                            the information provided is accurate, complete, or up-to-date. Your use of
                                            the Website is at your own risk.</p>

                                        <p>In no event will we be liable for any direct, indirect,
                                            incidental, or consequential damages arising from the use of the Website,
                                            including loss of data, profits, or business opportunities.</p>

                                        <h2 class="mt-4">12. Dispute Resolution</h2>

                                        <p> If you have a dispute with another user, you agree to release
                                            My Moving Journey from any liability or responsibility. You also waive any
                                            rights you may have under the laws of California or any other state that may
                                            apply to disputes related to these Terms.</p>

                                        <h2 class="mt-4">13. Indemnification</h2>

                                        <p class="mt-4">You agree to defend and indemnify us from any claims or
                                            damages arising from your use of the Website or your violation of these
                                            Terms. This includes reasonable legal fees and costs incurred in defending
                                            such claims.</p>

                                        <h2 class="mt-4">14. Privacy and Data Usage</h2>

                                        <p>Your use of the Website is governed by our Privacy Policy,
                                            which explains how we collect, use, and protect your personal data. By using
                                            our Website, you consent to the collection and use of your information as
                                            described in the Privacy Policy.</p>

                                        <h2 class="mt-4">15. Content Ownership and Intellectual Property</h2>

                                        <p>We respect the intellectual property rights of others and
                                            require you to do the same. If you believe your intellectual property rights
                                            have been infringed upon, please notify us with the necessary documentation.
                                        </p>

                                        <h2 class="mt-4">16. Links to Third-Party Websites</h2>

                                        <p>Our Website may contain links to third-party websites. These
                                            links are provided solely for convenience and do not imply an endorsement of
                                            the content found on those sites. We are not responsible for any content or
                                            services provided by third-party websites.</p>

                                        <h2 class="mt-4">17. Service Modifications</h2>

                                        <p>We reserve the right to modify, suspend, or discontinue any
                                            part of our Website at any time. We will not be liable for any disruptions,
                                            delays, or loss of services caused by such changes.</p>

                                        <h2 class="mt-4">18. Legal Compliance</h2>

                                        <p>By using the Website, you agree to comply with all applicable
                                            laws, including international laws relating to data transmission and online
                                            conduct.</p>

                                        <h2 class="mt-4">19. Governing Law</h2>

                                        <p>These Terms are governed by the laws of the Republic of
                                            Bulgaria. Any disputes related to the Website will be resolved according to
                                            Bulgarian law and in its courts.</p>

                                        <h2 class="mt-4">20. Miscellaneous</h2>

                                        <p>These Terms, together with the Privacy Policy and any
                                            applicable legal notices, constitute the entire agreement between you and us
                                            regarding your use of the Website. Any provision found to be invalid will
                                            not affect the remaining provisions.</p>









                                    </div>

                                </div>

                            </section>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>


    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "name": "Terms of Service",
  "url": "https://mymovingjourney.com/terms-of-service",
  "description": "Read our terms of service and legal policies for using MyMovingJourney platform"
}
</script>

    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebSite",
  "name": "MyMovingJourney",
  "url": "https://mymovingjourney.com",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "https://mymovingjourney.com/search?q={search_term_string}",
    "query-input": "required name=search_term_string"
  }
}
</script>

    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Home",
      "item": "https://mymovingjourney.com"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Terms of Service",
      "item": "https://mymovingjourney.com/terms-of-service"
    }
  ]
}
</script>
@endsection
